fosslib/frappe_api/views.py
from flask import Blueprint, flash, render_template

from fosslib.books.models import Book
from fosslib.utils import flash_form_errors
from .forms import ImportDataForm
from .frappe_api import get_n_books_from_api

blueprint = Blueprint(
    "frappe_api",
    __name__,
    url_prefix="/import_books",
)


@blueprint.route("/frappe/", methods=("GET", "POST"))
async def import_books():
    """
    Async view for importing data. Async so that the program can
    run fast and exit before the HTTP request times out
    """
    form = ImportDataForm()

    if form.validate_on_submit():
        await fetch_books_from_form(form)

    flash_form_errors(form)
    return render_template("import_books/frappe.html", form=form)


async def fetch_books_from_form(form):
    """Fetches the books from the farm and flashes the appropriate messages if any"""
    count = form.count.data
    title = form.title.data
    authors = form.authors.data
    isbn = form.isbn.data
    publisher = form.publisher.data

    total_results = 0
    added_count = 0
    duplicates_count = 0

    async for book in get_n_books_from_api(
        count, title=title, authors=authors, isbn=isbn, publisher=publisher
    ):
        total_results += 1

        # TODO: add book to DB, on conflict do nothing
        # figure out how to do it with SQLAlchemy
        if Book.query.get(book.id) is None:
            book.save()
            added_count += 1
        else:
            duplicates_count += 1

    if total_results == 0:
        flash("No results found for given search params", "danger")
    else:
        flash(
            f"Got {total_results} results from API. Imported {added_count} books, {duplicates_count} were duplicates",
            "success",
        )

fosslib/members/views.py
from flask import Blueprint, current_app, flash, render_template
from sqlalchemy.exc import IntegrityError

from fosslib.utils import Pagination, flash_form_errors, get_gravatar_image_url
from .forms import MemberForm
from .models import Member


blueprint = Blueprint("members", __name__, url_prefix="/members")


@blueprint.route("/", methods=("GET",))
def list():
    template_path = "members/list.html"

    query = get_member_query_from_request_args()
    pagination = Pagination(query)

    return render_template(template_path, pagination=pagination)


@blueprint.route("/show/", methods=("GET",))
def show():
    template_path = "members/show.html"

    return render_template("layout.html")


@blueprint.route("/create/", methods=("GET", "POST"))
def create():
    template_path = "members/create.html"

    form = MemberForm()
    if form.validate_on_submit():
        member = Member()
        form.populate_obj(member)

        member.gravatar_url = get_gravatar_image_url(member.email)

        # some room for improvemen with error handling here
        try:
            member.save()
            flash("Member added!", "success")
        except IntegrityError as e:
            current_app.logger.info(f"IntegrityError: {e}")
            flash(
                "There was some error while trying to add the "
                "new member. Maybe the email is already in use?",
                "danger",
            )
            return render_template(template_path, form=form)

    flash_form_errors(form)
    return render_template(template_path, form=form)


def get_member_query_from_request_args():
    query = Member.query

    # TODO: add support for search terms

    return query

fosslib/templates/index.html
{% extends 'layout.html' %}

{% block content %}


<h1>Hello world</h1>
<p>Lorem ipsum idor amet</p>
{% endblock %}

fosslib/templates/layout.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <title>
      FOSS Library
    </title>

    <meta charset="UTF-8">
    <meta name="description" content="Open source library management">
    <meta name="keywords" content="FOSS, Open Source, Library">
    <meta name="author" content="Kaustubh Maske Patil">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link
      rel="icon"
      type="image/svg+xml"
      href="{{ url_for('static', filename='build/img/favicon.svg') }}"
    />

    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='build/main_css.bundle.css') }}"
    />

    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='build/main_scss.bundle.css') }}"
    />

  </head>

  <body class="bg-light">

    {% include 'navbar.html' %}

    <main role="main">

      <div class="container border border-primary" style="background-color: #FBFEF9;">

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="mt-2 alert alert-{{ category }} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            <!-- end .alert -->
            {% endfor %}
          </div>
          <!-- end col-md -->
        </div>
        <!-- end row -->
        {% endif %}
        {% endwith %}

        {% block content %}
        {% endblock %}
      </div>

    </main>

    {% block js %}{% endblock %}

    <script src="{{ url_for('static', filename='build/main_js.bundle.js') }}"></script>

  </body>

</html>

fosslib/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-light text-primary mb-2">
  <a class="navbar-brand text-primary fs-1 mx-2" href="/">
    <img width="50" height="50" src="{{ url_for('static', filename='build/img/icon.svg') }}"></img>
    FossLib
  </a>
  <button class="navbar-toggler" style="box-shadow: none;" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      {% if request.path.startswith("/books/") %}
      <li class="nav-item bg-primary text-light active mx-1 fs-5">
      {% else %}
      <li class="nav-item text-primary mx-1 fs-5">
      {% endif %}
        <a class="nav-link text-reset px-3 py-0" href="{{ url_for('books.list') }}">
          Books
        </a>
      </li>

      {% if request.path.startswith("/members/") %}
      <li class="nav-item bg-primary text-light active mx-1 fs-5">
      {% else %}
      <li class="nav-item text-primary mx-1 fs-5">
      {% endif %}
        <a class="nav-link text-reset px-3 py-0" href="{{ url_for('members.list') }}">
          Members
        </a>
      </li>

      {% if request.path.startswith("/import_books/") %}
      <li class="nav-item bg-primary text-light active mx-1 fs-5">
      {% else %}
      <li class="nav-item text-primary mx-1 fs-5">
      {% endif %}
        <a class="nav-link text-reset px-3 py-0" href="{{ url_for('frappe_api.import_books') }}">
          Import books
        </a>
      </li>
    </ul>

    <form class="d-flex mx-2" action="{{ url_for('books.list') }}">
      <div class="input-group me-2">
        <input class="form-control border border-primary" style="box-shadow: none;" name="q" type="search" placeholder="Search" value="{{ request.args.get('q', '') }}" aria-label="Search">
        <button class="btn btn-outline-primary text-reset text-decoration-none bg-body" style="box-shadow: none;" type="submit">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
          </svg>
        </button>
      </div>
    </form>
  </div>
</nav>