fosslib/members/models.py
from fosslib.database import CRUDMixin, db


class Member(db.Model, CRUDMixin):
    __tablename__ = "members"

    id = db.Column(db.Integer, primary_key=True)

    first_name = db.Column(db.String)
    last_name = db.Column(db.String)
    email = db.Column(db.String, unique=True)

    gravatar_url = db.Column(db.String)
    dues_paid = db.Column(db.Integer, default=0)

fosslib/members/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.fields.html5 import EmailField
from wtforms.validators import Email, InputRequired


class MemberForm(FlaskForm):
    first_name = StringField(validators=[InputRequired()])
    last_name = StringField(validators=[InputRequired()])
    email = EmailField(validators=[InputRequired(), Email()])

fosslib/members/__init__.py
from . import views, models  # noqa: F401

fosslib/members/views.py
from flask import Blueprint, current_app, flash, render_template
from sqlalchemy.exc import IntegrityError

from fosslib.utils import Pagination, flash_form_errors, get_gravatar_image_url
from .forms import MemberForm
from .models import Member


blueprint = Blueprint("members", __name__, url_prefix="/members")


@blueprint.route("/", methods=("GET",))
def list():
    template_path = "members/list.html"

    query = get_member_query_from_request_args()
    pagination = Pagination(query)

    return render_template(template_path, pagination=pagination)


@blueprint.route("/show/", methods=("GET",))
def show():
    template_path = "members/show.html"

    return render_template("layout.html")


@blueprint.route("/create/", methods=("GET", "POST"))
def create():
    template_path = "members/create.html"

    form = MemberForm()
    if form.validate_on_submit():
        member = Member()
        form.populate_obj(member)

        member.gravatar_url = get_gravatar_image_url(member.email)

        # some room for improvemen with error handling here
        try:
            member.save()
            flash("Member added!", "success")
        except IntegrityError as e:
            current_app.logger.info(f"IntegrityError: {e}")
            flash(
                "There was some error while trying to add the "
                "new member. Maybe the email is already in use?",
                "danger",
            )
            return render_template(template_path, form=form)

    flash_form_errors(form)
    return render_template(template_path, form=form)


def get_member_query_from_request_args():
    query = Member.query

    # TODO: add support for search terms

    return query

fosslib/templates/members/create.html
{% extends 'layout.html' %}

{% block content %}

<div class="container my-4">
  <h1 class="text-secondary mb-4 fs-2">Members <i class="fas fa-angle-right fa-xs"></i> Create</h1>

  <div class="container">

    <form method="POST">

      {{ form.csrf_token }}

      <div class="row g-2 mb-3">
        <div class="col-sm-12 col-md-6">
          {{ form.first_name.label(class="form-label") }}
          {{ form.first_name(class="form-control") }}
        </div>

        <div class="col-sm-12 col-md-6">
          {{ form.last_name.label(class="form-label") }}
          {{ form.last_name(class="form-control") }}
        </div>
      </div>

      <div class="mb-3">
        <div class="col-12">
          {{ form.email.label(class="form-label") }}
          {{ form.email(class="form-control") }}
        </div>
      </div>

      <button class="btn btn-primary mb-3" type="submit">
        Submit
      </button>

    </form>

  </div>

</div>
{% endblock %}

fosslib/templates/members/list.html
{% extends 'layout.html' %}

{% block content %}
<div class="container my-4">
  <div class="d-flex justify-content-between align-items-stretch">
    <h1 class="text-secondary mb-4 fs-2">Members <i class="fas fa-angle-right fa-xs"></i> List</h1>
    <a class="text-reset text-decoration-none" href="{{ url_for('members.create') }}">
      <i class="fas fa-user-plus fa-2x"></i>
    </a>
  </div>

  <div class="container mx-auto">

    {% for member in pagination.items %}
    <div class="row p-2 border border-light rounded my-2 text-secondary">

      <div class="col-2">
        <a class="text-reset text-decoration-none" href="{{ url_for('members.show', id=member.id) }}">
          <img class="img-thumbnail mx-auto d-block rounded-circle" width="80" src="{{ member.gravatar_url }}" />
        </a>
      </div>

      <div class="col-2 d-flex align-items-center fw-bold">
        <a class="text-reset text-decoration-none" href="{{ url_for('members.show', id=member.id) }}">
          {{ member.first_name }} {{ member.last_name }}
        </a>
      </div>

      <div class="col-2 d-flex align-items-center">
        <a class="text-reset" href="mailto:{{ member.email }}">
          {{ member.email }}
        </a>
      </div>

      <div class="col-2 d-flex align-items-center">
        <span class="fw-bold">Paid dues: &nbsp;</span>
        Rs. {{ member.dues_paid }}
      </div>

    </div>
    {% endfor %}

  </div>

</div>
{% endblock %}